blog/urls.py
from django.urls import path
from .import views


app_name = 'blog'

# https://docs.djangoproject.com/en/4.0/topics/http/urls/#pathconverters.
urlpatterns = [
    path('search/', views.post_search, name='post_search'),
    path('publication/', views.post_publication, name='post_publication'), 
    path('<slug:post>/',views.post_detail, name='post_detail'),  
    path('', views.post_list, name='post_list'), 
    path('<slug:post_slug>/share/',views.post_share, name='post_share'),
    path('tag/<str:tag_slug>/',views.post_list, name='post_list_by_tag'),  
]

ebdjango/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
]

blog/models.py
from django.db import models
from django.utils import timezone
from datetime import datetime
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.text import slugify


# QuerySet Reference
# https://docs.djangoproject.com/en/4.0/ref/models/querysets/



# QuerySet Manager
# https://docs.djangoproject.com/en/4.0/topics/db/managers/
class PublishedManager(models.Manager):
    def get_queryset(self):
        return super(PublishedManager,self).get_queryset().filter(status='published')


# Model Reference
# https://docs.djangoproject.com/en/4.0/ref/models/fields/
class Post(models.Model):
    STATUS_CHOICES = (
        ('draft', 'Draft'),
        ('published', 'Published'),
    )

    TAG_CHOICES = (
        ('mundo', 'Mundo'),
        ('esportes','Esportes'),
        ('tecnologia','Tecnologia'),
        ('natureza','Natureza'),
        ('cultura','Cultura'),
        ('dinheiro','Dinheiro'),
        ('política','Política'),
        ('saúde','Saúde'),
        ('turismo','Turismo'),
        ('games','Games'),
    )

    title = models.CharField(max_length=250, unique = True,)
    slug = models.SlugField(max_length=250, default=None)
    author = models.ForeignKey(User, on_delete=models.CASCADE, default='1') #related_name='blog_posts'
    body = models.TextField(max_length=5000)

    #https://docs.djangoproject.com/en/4.0/ref/models/fields/#datefield
    publish = models.DateTimeField(default=timezone.now)
    created_date = models.DateField(auto_now_add=True)
    created_time = models.TimeField(auto_now_add=True)
    updated_date = models.DateField(auto_now=True)
    updated_time = models.TimeField(auto_now=True)
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='published')
    tag = models.CharField(max_length=10, choices=TAG_CHOICES, default='mundo')


    #https://docs.djangoproject.com/en/4.0/topics/db/managers/
    #objects serve para obter tanto as publicações published ou draft
    objects = models.Manager() # The default manager.
    #serve apenas para obter as publicações published
    published = PublishedManager()


# Class Meta reference
# https://docs.djangoproject.com/en/4.0/ref/models/options/
    class Meta:
        ordering = ('-created_date',)
    
    def __str__(self):
        return self.title

    # Gerar SLUG
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse ('blog:post_detail', args=[self.slug])
        # return f'blog/{self.slug}/'



class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE, )
    name = models.CharField(max_length=40)
    email = models.EmailField(max_length=80)
    body = models.TextField(max_length=100)
    publish = models.DateTimeField(default=timezone.now)
    created_date = models.DateField(auto_now_add=True)
    created_time = models.TimeField(auto_now_add=True)
    updated_date = models.DateField(auto_now=True)
    updated_time = models.TimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering = ('publish',)

    def __str__(self):
        return f'Comment by {self.name} on {self.post}'

blog/forms.py
# https://docs.djangoproject.com/en/4.0/topics/forms/
# https://docs.djangoproject.com/en/4.0/ref/forms/fields/
# https://docs.djangoproject.com/en/4.0/ref/forms/widgets/
# https://docs.djangoproject.com/en/4.0/topics/forms/modelforms/

from django import forms    
from .models import Comment, Post

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('name', 'email', 'body')
        widgets = {
            'name': forms.TextInput(attrs={'placeholder':'Nome', 'size': 10, 'title': 'Your name' }), 
            'email': forms.EmailInput(attrs={'placeholder':'E-mail',}),
            'body': forms.Textarea(attrs={'placeholder':'Comentário', }),
            }
        labels = {
            'name': (''),
            'email': (''),
            'body': (''),
            }
    

class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title' , 'tag', 'body',)
        widgets = {
            'title' : forms.TextInput(attrs={'placeholder':'Título'}),
            'body' : forms.Textarea(attrs={'placeholder' : 'Descrição'}),
            'tag' : forms.Select(attrs={'class' : 'text',})
        }
        labels = {
            'title' : (''),
            'body' : (''), 
        }

        #https://docs.djangoproject.com/en/4.0/ref/models/fields/#error-messages
        error_messages = {
            'title' : {
                'unique' : ('Já existe uma publicação com este título')
            },
        }


    #Validação form customizada
    #https://docs.djangoproject.com/en/4.0/ref/forms/validation/#cleaning-and-validating-fields-that-depend-on-each-other
    def clean(self):
        cleaned_data = super().clean()
        title = cleaned_data.get("title")

        if Post.objects.filter(title__iexact=title).exists():
            msg = "Já existe uma publicação com este título"
            self.add_error('title', msg)




# Esse form não tem model, por isso é feito apenas com forms.Form
class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25, label='', widget=forms.TextInput(attrs={'placeholder':'Nome'}))
    email = forms.EmailField(label='', widget=forms.EmailInput(attrs={'placeholder':'E-mail de'}))
    to = forms.EmailField(label='', widget=forms.EmailInput(attrs={'placeholder':'E-mail para'}))
    comments = forms.CharField(label='', required=False, widget=forms.Textarea(attrs={'placeholder':'Comentário'}))

blog/views.py
from django.shortcuts import redirect, render, get_object_or_404
from .models import Post, User
from .forms import EmailPostForm, CommentForm, PostForm
from django.core.mail import send_mail
import random
from django.core.paginator import Paginator
from django.db.models import Q



def post_detail(request, post):
    post = get_object_or_404(Post, slug=post, status='published')
    slug = post.slug


    # List of active comments for this post
    comments = post.comment_set.filter(active=True)

    new_comment = None

    if request.method == 'POST':
        # A comment was posted
        comment_form = CommentForm(request.POST)

        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database


            new_comment.save()

            return redirect(f'/{slug}')
    else:
        comment_form = CommentForm()

    paginator = Paginator(comments, 5) # Show 25 contacts per page.

    page_number = request.GET.get('page')
    page_obj = paginator.get_page(page_number)
       
    # List of similar posts
    similar_posts = Post.published.exclude(id=post.id)
   

    return render(request, 'detail.html',
                {
                    'post': post, 
                    'new_comment': new_comment, 
                    'comments': comments, 
                    'comment_form': comment_form, 
                    'similar_posts': similar_posts,
                    'page_obj': page_obj,
                })


def post_share(request, post_slug):
    # Retrieve post by id
    post = get_object_or_404(Post, slug=post_slug, status='published')
    sent = False

    if request.method == 'POST':
        # Form was submitted
        share_form = EmailPostForm(request.POST)

        if share_form.is_valid():
             # Form fields passed validation
            cd = share_form.cleaned_data

            post_url = request.build_absolute_uri(post.get_absolute_url())
            subject = f"{cd['name']} recomendou você ler {post.title}"
            message = f"Leia {post.title} no link {post_url}\n\n" \
                      f"Comentário de '{cd['name']}': {cd['comments'].title()}"
            send_mail(subject, message, cd['to'], ['projetodjango123@gmail.com'])
            sent = True
            # ... send email

    else:
        share_form = EmailPostForm()

    return render(request, 'share.html', 
                {
                    'post': post, 
                    'share_form': share_form, 
                    'sent': sent,                            
                })


def post_list(request, tag_slug=None):

    post_list = (Post.published.all())
    post_list_id = [x.id for x in post_list]
    post_random_id = random.sample(post_list_id, len(post_list_id))

    post_list_random = [Post.published.get(id=x) for x in post_random_id]
    random_posts = post_list_random[2::]

    post_last = None
    if post_list:
        post_last = post_list.latest('created_date','created_time')

    post_list_tag = None
    selected_tag = None

    if tag_slug:
        post_list_tag = post_list.filter(tag=tag_slug)
        selected_tag = tag_slug
        


    return render(request,'list.html',
                {
                    'selected_tag' : selected_tag,
                    'post_list_tag': post_list_tag,
                    'post_list_random': post_list_random,
                    'post_last': post_last,
                    'random_posts': random_posts,            
                })




def post_search(request):
    #Não precisa de render no method GET pelo fato que o input sempre vai ser POST
    
    list_query = None

    #O FORM AQUI FOI COM O .GET PORQUE NÃO TEM UM FORM NO FORM.PY PRA USAR O CLEANED_DATA
    if request.method == 'POST':
        search_form = request.POST.get('search')
        list_query = Post.published.filter(Q(body__icontains=search_form) | Q(title__icontains=search_form) )
        return render(request, 'search.html', 
                        {
                            'list_query' : list_query
                        })



def post_publication(request):
    post_form = PostForm()   

    if request.method == 'POST':
        post_form = PostForm(request.POST)

        if post_form.is_valid():
            post_form.save()
            
            return redirect(f'/')
            

    return render (request, 'publication.html',
                    {
                        'post_form' : post_form,
                    })

blog/templates/base.html
<!-- Template tags -->
<!-- https://docs.djangoproject.com/en/4.0/ref/templates/builtins/ -->

{% load static %}

<!DOCTYPE html>
<html lang="pt-br">

<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'css/styless.css' %}">

   <title>{% block title %}Base{% endblock %}</title> 
</head>

<body>
  <header class="header-container">
    <div class="header-content">
      <div>
        <a href="{% url 'blog:post_list' %}">
          <h1>BLOG</h1>
        </a>
      </div>
      <div class="publication">
        <a href="{% url 'blog:post_publication' %}">
          <h2>Publique aqui</h2>
        </a>
      </div>
      <div class="header-item-form">
        <div class="header-form">
          <form action="{% url 'blog:post_search' %}" method="post">
            {% csrf_token %}
            <input type="text" name="search" placeholder="Procurar" required>
          </form>
        </div>
      </div>
    </div>

    <nav class="nav-container">
      <ul class="nav-content">
        <li class="li-underline">
          <a class="underline" href="{% url 'blog:post_list_by_tag' 'mundo' %}">Mundo</a>
        </li>
        <li class="li-underline">
          <a class="underline" href="{% url 'blog:post_list_by_tag' 'esportes' %}">Esportes</a>
        </li>
        <li class="li-underline">
          <a class="underline" href="{% url 'blog:post_list_by_tag' 'saude' %}">Saúde</a>
        </li>
        <li class="li-underline">
          <a class="underline" href="{% url 'blog:post_list_by_tag' 'tecnologia' %}">Tecnologia</a>
        </li>
        <li class="li-underline">
          <a class="underline" href="{% url 'blog:post_list_by_tag' 'games' %}">Games</a>
        </li>
        <li class="li-underline">
          <a class="underline" href="{% url 'blog:post_list_by_tag' 'natureza' %}">Natureza</a>
        </li>
        <li class="li-underline">
          <a class="underline" href="{% url 'blog:post_list_by_tag' 'cultura' %}">Cultura</a>
        </li>
        <li class="li-underline">
          <a class="underline" href="{% url 'blog:post_list_by_tag' 'dinheiro' %}">Dinheiro</a>
        </li>
        <li class="li-underline">
          <a class="underline" href="{% url 'blog:post_list_by_tag' 'politica' %}">Política</a>
        </li>
        <li class="li-underline">
          <a class="underline" href="{% url 'blog:post_list_by_tag' 'turismo' %}">Turismo</a>
        </li>
      </ul>
    </nav>
  </header>

  {% block content %}
  {% endblock %}

  <footer class="footer-container">
    <div class="footer-content">
      <div class="footer-item-sobre">
        <div style="width: 100%;"><h2>Sobre</h2></div>
        <div><p> Projeto construído com o intuito de praticar HTML, CSS e
          Django. Leia os posts de terceiros e publique suas escritas
          nos mais diversos temas disponíveis. Divirta-se! :).</p></div>
      </div>

      <div class="footer-item-categorias">
        <h2>Categorias</h2>
        <div class="footer-item-categorias-categorias">
          <ul class="footer-item-categorias-categorias-list">
            <li>
              <a href="{% url 'blog:post_list_by_tag' 'mundo' %}">Mundo</a>
            </li>
            <li>
              <a href="{% url 'blog:post_list_by_tag' 'esportes' %}">Esportes</a>
            </li>
            <li>
              <a href="{% url 'blog:post_list_by_tag' 'saude' %}">Saúde</a>
            </li>
            <li>
              <a href="{% url 'blog:post_list_by_tag' 'tecnologia' %}">Tecnologia</a>
            </li>
            <li>
              <a href="{% url 'blog:post_list_by_tag' 'games' %}">Games</a>
            </li>
            <li>
              <a href="{% url 'blog:post_list_by_tag' 'natureza' %}">Natureza</a>
            </li>
            <li>
              <a href="{% url 'blog:post_list_by_tag' 'cultura' %}">Cultura</a>
            </li>
            <li>
              <a href="{% url 'blog:post_list_by_tag' 'dinheiro' %}">Dinheiro</a>
            </li>
            <li>
              <a href="{% url 'blog:post_list_by_tag' 'politica' %}">Política</a>
            </li>
            <li>
              <a href="{% url 'blog:post_list_by_tag' 'turismo' %}">Turismo</a>
            </li>
          </ul>
        </div>
      </div>

    </div>
    <div class="footer-content-copyright">
      <div class="footer-item-copyright">
        <h5>Copyright © 2022 All Rights Reserved by Weslley.</h5>
      </div>
      <div class="footer-item-icones">
        <a href="https://github.com/WeslleyxD/WeslleyxD" target="_blank"><img src="{% static 'img/github.svg' %}"></a>
        <a href="https://www.linkedin.com/in/weslley-pablo-7b0734222/" target="_blank"><img src="{% static 'img/linkedin.svg' %}" ></a>
      </div>
    </div>
  </footer>
</body>

</html>

blog/templates/detail.html
{% extends "base.html" %}


{% block title %} {{post.title}} {% endblock %}


{% block content %}
<div class="u-container">
    <div class="u-content-pr">
        <div class="u-item-title">
            <a href="{{ post.get_absolute_url }}">
                <h2>{{ post.title|capfirst }}</h2>
            </a>
        </div>
        <hr>
        <div class="l-item-tag">
            <a href="{% url 'blog:post_list_by_tag' post.tag %}">
                <h5>em {{post.tag|capfirst}}</h5>
                <h6>{{ post.publish|date:"d M, H:i" }}</h6>
            </a>
        </div>

        <div class="u-item-body">
            <p>{{post.body}}</p>
        </div>
        <div class='u-item-share'>
            <h5>
                <a href="{% url 'blog:post_share' post.slug %}">
                    Compartilhar
                </a>
            </h5>
        </div>
    </div>
    <div class="u-content-mais">
        <div class="u-item-mais">
            <h2>Mais publicações</h2>
        </div>
        <div class="u-item-list">
            {% for similar_post in similar_posts|slice:":10" %}
            <ul class="u-item-title-mais">
                <li><a href="{{ similar_post.get_absolute_url }}">{{similar_post.title|capfirst}}</a></li>
            </ul>

            {% empty %}

            <h3>Aguardando novas publicações.</h3>

            {% endfor %}
        </div>
    </div>
</div>

<div class="comments-container">
    <h2>
        {% with total_comments=comments.count %}
        {{ total_comments }} Comentário{{ total_comments|pluralize }}
        {% endwith %}
    </h2>


    <div class="comments-content">
        {% for comment in page_obj %}
        <div class="comments-items-descricao">
            <div class="c-items">
                <div class="c-item-user">
                    <p> Comentário de {{ comment.name|capfirst }}:</p>
                </div>

                <div class="c-item-created">
                    <h6>{{ comment.created }}</h6>
                </div>
            </div>
        </div>
        <div class="comments-items-body">
            <div>
                <p>{{ comment.body}}</p>
            </div>
        </div>
        <hr>

        {% empty %}

        <p>Seja o primeiro a comentar na publicação</p>

        {% endfor %}

        <!-- Paginação -->
        {% include "pagination.html" with page_obj=page_obj %}


        <div class="form-container">
            <form method="post">
                <h2>Adicione um novo comentário</h2>
                {{ comment_form.as_p }}
                {% csrf_token %}
                <input type="submit" value="Adicionar">
            </form>
        </div>

    </div>

</div>


{% endblock %}

blog/templates/list.html
{% extends "base.html" %}


{% block title %} Mais publicações em {{selected_tag}} {% endblock %}


{% block content %}


{% if post_list_tag %}

<div class="u-container">
    <div class="s-content-mais">
        <div class="u-item-mais">
            <h2>Publicações em "{{selected_tag|capfirst}}"</h2>
        </div>
        <div class="u-item-list">
            {% for obj_tag in post_list_tag %}
            <ul class="u-item-title-mais">
                <li><a href="{{ obj_tag.get_absolute_url }}">{{obj_tag.title|capfirst}}</a></li>
            </ul>
            {% endfor %}
        </div>
    </div>
</div>


{% else %}


<div class="l-container">
    {% for obj_list in post_list_random|slice:":2" %}

    <div class="l-content-1">
        <div class="l-content">
            <div class="l-item-tag">
                <a href="{% url 'blog:post_list_by_tag' obj_list.tag %}">
                    <h5>Em {{obj_list.tag|capfirst}}</h5>
                </a>
            </div>

            <div class="l-item-title">
                <a href="{{ obj_list.get_absolute_url }}">
                    <h2>{{obj_list.title|capfirst}}</h2>
                </a>
                <h6>{{obj_list.publish|date:"d M, H:i"}}</h6>
            </div>

            <div class="l-item-body">
                <p>{{obj_list.body|truncatechars:80|linebreaks}}</p>
            </div>

            <div class="l-item-link">
                <a href="{{ obj_list.get_absolute_url }}"><span> Continue lendo...</span></a>
            </div>
        </div>
    </div>

    {% endfor %}
</div>

<div class="u-container">
    <div class="u-content-pr">
        <div class="u-item-pub">
            <h3><span> Publicação Recente </span></h3>
        </div>
        <hr>
        <div class="u-item-title">
            <a href="{{ post_last.get_absolute_url }}">
                <h2>{{post_last.title|capfirst }}</h2>
            </a>
        </div>
        <div class="u-item-body">
            <p>{{post_last.body|capfirst }}</p>
        </div>
    </div>
    <div class="u-content-mais">
        <div class="u-item-mais">
            <h2>Mais publicações</h2>
        </div>
        <div class="u-item-list">
            {% for post in random_posts|slice:":10" %}
            <ul class="u-item-title-mais">
                <li><a href="{{ post.get_absolute_url }}">{{post.title|capfirst}}</a></li>
            </ul>
            {% endfor %}
        </div>
    </div>
</div>


{% endif %}

{% endblock %}

blog/templates/pagination.html
    {% if page_obj.has_other_pages %}
        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page={{ page_obj.previous_page_number }}">&laquo; {{ page_obj.previous_page_number }}</a>
                {% endif %}
        
                <span class="current">
                    {{ page_obj.number }}
                </span>
                
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}">{{ page_obj.next_page_number }} &raquo;</a>
                {% endif %}
            </span>
        </div>
    {% else %}

    {% endif %}

blog/templates/publication.html
{% extends "base.html" %}

{% block content %}

<div class="comments-container">
    <div class="comments-content">
        <div class="form-container">
            <form method="post">
                <h2>Adicione uma publicação</h2>
                {{ post_form.as_p }}
                {% csrf_token %}
                <input type="submit" value="Publicar">
            </form>
        </div>       
    </div>
</div>



{% endblock %}

blog/templates/search.html
{% extends "base.html" %}


{% block content %}

{% if list_query %}
<div class="u-container">
    <div class="s-content-mais">
        <div class="u-item-mais">
            {% with total_query=list_query.count %}
            <h2>{{ total_query }} item{{ total_query|pluralize }} achado{{ total_query|pluralize}}</h2>
            {% endwith %}
        </div>
        <div class="u-item-list">
            {% for post in list_query %}
            <ul class="u-item-title-mais">
                <li><a href="{{ post.get_absolute_url }}">{{post.title|capfirst}}</a></li>
            </ul>
            {% endfor %}
        </div>
    </div>
</div>


{% else %}


<div class="u-item-mais">
    <h1>Nenhum item achado</h1>
</div>


{% endif %}

{% endblock %}

blog/templates/share.html
{% extends "base.html" %}

{% block title %}Compartilhe a publicação{% endblock %}


{% block content %}
<div class="send-container">
    {% if sent %}
    <div class="send-content-sucess">
        <!-- <h1>E-mail successfully sent</h1> -->
        <!-- <p>"{{ post.title }}" foi enviado com sucesso para {{ share_form.cleaned_data.to }}.</p> -->
        <h1>Serviço Indisponível</h1>
        <p>Não tenho acesso à AWS (SES) para enviar e-mail.</p>
    </div>

    {% else %}

    <div class="send-content-form">
        <div class="form-container">
            <form method="post">
                <h2>Compartilhe a publicação "{{ post.title }}" por e-mail</h2>
                {% csrf_token %}
                {{ share_form.as_p }}
                <input type="submit" value="Send e-mail">
            </form>

        </div>
    </div>

    {% endif %}
</div>


{% endblock %}